// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-variants/CardFirst.tsx": () => import("../components/mockups/landing-variants/CardFirst.tsx"),
  "./components/mockups/landing-variants/CompactCommand.tsx": () => import("../components/mockups/landing-variants/CompactCommand.tsx"),
  "./components/mockups/landing-variants/SplitScreen.tsx": () => import("../components/mockups/landing-variants/SplitScreen.tsx")
};
